export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const CATEGORY_TOP_REQUEST = "CATEGORY_TOP_REQUEST";
export const CATEGORY_TOP_SUCCESS = "CATEGORY_TOP_SUCCESS";
export const CATEGORY_TOP_FAIL = "CATEGORY_TOP_FAIL";


